config/routes.rb
Wikful::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :sessions
  resources :users

  get "welcome/index"

  root 'welcome#index'
 resources :categories, :articles, :users

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true
	validates :content, presence: true
	validates :categories, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article 
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :articles
	validates_uniqueness_of :email
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
  def get_categories
    @categories = Category.all.order(:name)
  end
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/article_controller.rb
class ArticlesController < ApplicationController
	def index

	end

	def show

	end

	def create

	end 
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authorize, only: [:new]
	
	def index
		@articles = Article.order(updated_at: :desc).limit(25)
	end

	def show
		@article= Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end 

	private 
		def article_params
			params.require(:article).permit(:title, :content, :category_ids => [])
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all.order(:name)
	end

	def show
		@category = Category.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password]) # get this for free from has_secure_password
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged in" 
  		#redirect_to Welcome#index, notice: "Logged in"
  	else 
  		flash.now.alert = "Email or password invalid"
  		#render "new" #I want to try and do this from the nav, so I want to do it without rendering a new page
  	end
  end

  def destroy
	session[:user_id] = nil
	redirect_to root_url, notice: "Logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
	end

	private
		def user_params
			params.require(:user).permit(:email, :name, :password, :password_confirmation)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@recent_articles = Article.order(updated_at: :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<div class="control-group">
		<%= f.label :title %>
		<div class="controls" >
			<%= f.text_field :title, :class => "span8" %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :content %>
		<div class="controls">
			<%= f.text_area :content, rows: "20", :class => "span8"  %>
		</div>
	</div>

	<div class="category-control">
		<%= f.label 'File under at least one category' %>
		<% Category.all.order(name: :asc).each do |category| %>
			<div>
				<%= check_box_tag "article[category_ids][]", category.id %>
				<%= category.name %>
			</div>
		<% end %>
	</div>

	<div class="form-actions">
		<%= f.submit nil %>
		<%= link_to 'Cancel', articles_path %>
	</div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<h1>This is the index view for Articles</h1>
<% @articles.each do |article| %>
  <div>
    <h3><%= link_to article.title, article %></h3>
  	<p>Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
    <p>Categories: 
		<% @article.categories.each do |category| %> 
			<%= link_to category.name, category %> 
		<% end %>
    </p>
    <p><%= truncate(article.content, length: 200) %></p>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>Write and Publish a New Article</h1>
<% if @article.errors.any? %>
<div class="error_message">
	<h2>You're missing some fields</h2>
	<ul>
		<% @article.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<div>
  <h1><%= @article.title %></h1>
  <p>Published <%= @article.created_at.strftime('%b %d, %Y') %></p>
  <p>Categories: 
		<% @article.categories.each do |category| %> 
			<%= link_to category.name, category %> 
		<% end %>
  </p>
  <div><%= @article.content %></div>
</div>

app/views/categories/index.html.erb
<h1 style="line-height: 1.5">Wikiful Categories</h1>
<% @categories.each do |category| %>
	<h4 style="text-align: center;"><%= link_to category.name, category %></h4>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %> Articles</h1>
<h3>There are <%= @category.articles.count %> articles fild under <%= @category.name %></h3>
<ul>
	<% @category.articles.order(:title).each do |article| %>
		<h4>
			<%= link_to article.title, article %>
		</h4>
		<p>
			<%= truncate(article.content, length: 200) %>
		</p>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikful</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Wikiful", root_path, :class => "brand" %>
       <div class="session-controls"> 
          <% if current_user %>
            <%= link_to "Log Out", session_path("current"), method: 'delete', :class => 'right btn btn-primary btn-mini' %>
            <p class="right" style="padding-right: 10px;">Logged in as <%= current_user.email %>.</p>
          <% else %>
            <div class="btn-group">
               <%= link_to "Sign Up", signup_path, :class => "btn btn-mini" %>
               <%= link_to "Log In", login_path, :class => "btn btn-mini" %>
            </div>
          <% end %>
       </div>
    </div>
  </div>
</div>
     <!-- <div class="form-container">
      	  <%= link_to "Sign Up", new_user_path, :class => "btn btn-mini" %>
	      <%= form_tag sessions_path do  %>
			  <div class="field">
			    <%= text_field_tag :email, params[:email], :placeholder => "Email" %> 
			  </div>
			  <div class="field">
			    <%= text_field_tag :password, params[:password], :type => "password", :placeholder => "Password" %> 
			  </div>
			  <div class="actions"><%= submit_tag "Log In" %></div>
		  <% end %>
		</div>
      <form class="navbar-form navbar-right" style="float: right;">
      		<div class="form-group">
      			<input type="text" placeholder="Email" class="form-control">
      		</div>
      		<div class="form-group">
      			<input type="password" placeholder="Password" class="form-control"> 
      		</div>
      		<button type="submit" class="btn btn-success">Sign in</button>
      </form>-->
<div class="container">
  <div class="row">
  	<div class="span4">
	    <% flash.each do |name, msg| %>
	      <%= content_tag :div, msg, id: "flash_#{name}" %>
	    <% end %>
    </div>
    <div class="span9"><%= yield %></div>
    <div class="span3 sidebar">
	  <div class="my-wiki-site">
	    <h4>My Wikiful</h4>
	    <ul>
	      <li><%= link_to "Write a Wiki", new_article_path %></li>
	    </ul>
	  </div>
	  <div class="categories-sidebar">
	    <h4>Categories</h4>
	    <ul>
	      <% @categories.each do |category| %>
	        <li><%= link_to category.name, category %></li>
	      <% end %>
	    </ul>
	  </div>
	  <div class="about">
	    <h4>About Wikiful</h4>
	    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto earum neque perspiciatis quia animi debitis quod repellat vitae explicabo. Sapiente aliquam reprehenderit id vitae atque ducimus facere molestias soluta?</p>
	  </div>
	</div>
  </div>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %> 
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %> 
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %> 
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> 
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Wikiful!</h1>
<h3>Here are some recent articles:</h3>
<% @recent_articles.each do |article| %>
	<h4><%= link_to article.title, article %></h4>
	<p>Posted on: <%= article.created_at.strftime('%b %d, %Y') %></p>
	<p>Categories: 
		<% article.categories.each do |category| %> 
			<%= link_to category.name, category %> 
		<% end %>
	</p>
	<p> <%= truncate(article.content, length: 100) %> <%= link_to 'Read more', article %></p>
<% end %>